# -*- coding: utf-8 -*-
"""Machine learning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vqweSoZnhaVP02ep5TIxuA-2IKipbPsM
"""

import pandas as pd

data = {
    'Sky': ['Sunny', 'Sunny', 'Rainy', 'Sunny'],
    'AirTemp': ['Warm', 'Warm', 'Cold', 'Warm'],
    'Humidity': ['Normal', 'High', 'High', 'High'],
    'Wind': ['Strong', 'Strong', 'Strong', 'Strong'],
    'Water': ['Warm', 'Warm', 'Warm', 'Cool'],
    'Forecast': ['Same', 'Same', 'Change', 'Change'],
    'EnjoySport': ['Yes', 'Yes', 'No', 'Yes']
}

df = pd.DataFrame(data)
df.to_csv('finds.csv', index=False)

print(df)
import pandas as pd

data = pd.read_csv('finds.csv')

concepts = data.iloc[:, :-1].values
target = data.iloc[:, -1].values

hypothesis = ['0'] * len(concepts[0])

print("Initial Hypthesis:")
print(hypothesis)

for i in range(len(target)):
    if target[i] == "Yes":
        for j in range(len(hypothesis)):
            if hypothesis[j] == '0':
                hypothesis[j] = concepts[i][j]
            elif hypothesis[j] != concepts[i][j]:
                hypothesis[j] = '?'

        print(f"After Positive Example {i+1}: {hypothesis}")

print("\nFinal Most Specific Hypothesis:")
print(hypothesis)

import pandas as pd

data = {
    'Sky': ['Sunny', 'Sunny', 'Rainy', 'Sunny'],
    'AirTemp': ['Warm', 'Warm', 'Cold', 'Warm'],
    'Humidity': ['Normal', 'High', 'High', 'High'],
    'Wind': ['Strong', 'Strong', 'Strong', 'Strong'],
    'Water': ['Warm', 'Warm', 'Warm', 'Cool'],
    'Forecast': ['Same', 'Same', 'Change', 'Change'],
    'EnjoySport': ['Yes', 'Yes', 'No', 'Yes']
}

df = pd.DataFrame(data)
df.to_csv('candidate.csv', index=False)

print(df)
import pandas as pd
import numpy as np

data = pd.read_csv('candidate.csv')

concepts = np.array(data.iloc[:, :-1])
target = np.array(data.iloc[:, -1])

specific_h = concepts[0].copy()
general_h = [["?" for i in range(len(specific_h))] for i in range(len(specific_h))]

print("Initial Specific Hypothesis")
print(specific_h)

print("\nInitial General Hypothesis")
for g in general_h:
    print(g)

for i, h in enumerate(concepts):

    if target[i] == "Yes":

        for x in range(len(specific_h)):
            if h[x] != specific_h[x]:
                specific_h[x] = '?'
                general_h[x][x] = '?'

    elif target[i] == "No":

        for x in range(len(specific_h)):
            if h[x] != specific_h[x]:
                general_h[x][x] = specific_h[x]
            else:
                general_h[x][x] = '?'

print("\nFinal Specific Hypothesis")
print(specific_h)

print("\nFinal General Hypothesis")

general_final = [g for g in general_h if g != ['?']*len(specific_h)]

for g in general_final:
    print(g)

import pandas as pd

data = {
    'Outlook':['Sunny','Sunny','Overcast','Rain','Rain','Rain','Overcast','Sunny','Sunny','Rain','Sunny','Overcast','Overcast','Rain'],
    'Temperature':['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild'],
    'Humidity':['High','High','High','High','Normal','Normal','Normal','High','Normal','Normal','Normal','High','Normal','High'],
    'Wind':['Weak','Strong','Weak','Weak','Weak','Strong','Strong','Weak','Weak','Weak','Strong','Strong','Weak','Strong'],
    'Play':['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']
}

df = pd.DataFrame(data)
df.to_csv('playtennis.csv', index=False)

print(df)
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
import matplotlib.pyplot as plt

data = pd.read_csv('playtennis.csv')

X = data.iloc[:, :-1]
y = data.iloc[:, -1]

encoders = {}

for column in X.columns:
    le = LabelEncoder()
    X[column] = le.fit_transform(X[column])
    encoders[column] = le

label = LabelEncoder()
y = label.fit_transform(y)

model = DecisionTreeClassifier(criterion='entropy', random_state=0)
model.fit(X, y)

plt.figure(figsize=(12,8))
tree.plot_tree(
    model,
    feature_names=X.columns,
    class_names=label.classes_,
    filled=True
)

plt.show()

# New Sample
new_sample = pd.DataFrame({
    'Outlook':['Sunny'],
    'Temperature':['Cool'],
    'Humidity':['Normal'],
    'Wind':['Weak']
})

for col in new_sample.columns:
    new_sample[col] = encoders[col].transform(new_sample[col])

prediction = model.predict(new_sample)

print("\nPrediction for New Sample:")
print("Play =", label.inverse_transform(prediction)[0])