# -*- coding: utf-8 -*-
"""ML C03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qed-hHK0LVsyo3Grwk68F6VzTo4K3vGM
"""

# Naive Bayes Algorithm using Iris Dataset

# Import Libraries
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Load Iris Dataset
iris = load_iris()

X = iris.data
y = iris.target

print("Feature Names:")
print(iris.feature_names)

print("\nTarget Names:")
print(iris.target_names)

# Split the Dataset into Training and Testing Sets
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42
)

# Create Naive Bayes Classifier
model = GaussianNB()

# Train the Model
model.fit(X_train, y_train)

# Predict Test Data
y_pred = model.predict(X_test)

# Display Results
print("\n-------------------------------")
print("Naive Bayes Classification Results")
print("-------------------------------")

print("\nAccuracy:")
print(accuracy_score(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Test with a New Sample
sample = [[5.1, 3.5, 1.4, 0.2]]

prediction = model.predict(sample)

print("\nNew Sample:", sample[0])
print("Predicted Class:", iris.target_names[prediction][0])